### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by hilinxinhui** [QuetzalCpp/DeepPilot#1]
Hello, I'm trying to replicate your algorithms. I hava configured the environment, but received the following error when running the code `train_deeppilot.py`:

```Shell
IOError: [Errno 2] No such file or directory: 'posenet.npy'
```

I found this file [here](https://github.com/rockkingjy/Model_Image2GPS_Tensorflow) (I'm not sure if it's the right file), but there are new problems:

```Shell
IOError: [Errno 2] No such file or directory: './dataset/ardrone_dataset/train/train.txt'
```

I noticed that the [dataset you provided on Gihub](https://inaoepedu-my.sharepoint.com/personal/carranza_inaoe_edu_mx/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fcarranza%5Finaoe%5Fedu%5Fmx%2FDocuments%2FDeepP%C3%AFlot%2FDeepPilot%5FDataset&originalPath=aHR0cHM6Ly9pbmFvZXBlZHUtbXkuc2hhcmVwb2ludC5jb20vOmY6L2cvcGVyc29uYWwvY2FycmFuemFfaW5hb2VfZWR1X214L0VzbHhWRHFjOXpCTW1pVjRtREg0OEtVQkFjQUh1MFlwdDFyWkxMNmlmT2p5b0E_cnRpbWU9dHk1Q1l0SGYyRWc) did not match the dataset used by the code (`./dataset/ardrone_dataset/train/train.txt` and `./dataset/ardrone_dataset/test/test.txt`).

At the same time, the `.h5` file generated by `train_deeppilot.py` is not the file used in `evaluation_mosaic-ximg.py`(x = 2, 4, 6, 8), and when I run the relevant code, I get the following error message:

```Shell
IOError: Unable to open file (unable to open file: name = 'models/models_2img/2img_roll_pitch_model.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

I'd like to know more about how to run your code. Can you give me some advice on these problems ?

**Comment by MOVAX19** [comment]
Hi, @A1kyl8N 
Did you figure out what the problem was? I'm having the same issue trying to figure out how to train the model

**Comment by QuetzalCpp** [comment]
Sorry for the late reply but you can find the additional resources at https://github.com/QuetzalCpp/DeepPilot/releases/tag/v2.0
